imports:
    - { resource: drupal.yml }
    - { resource: parameters.yml }
    - { resource: services.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    validation:      { enable_annotations: true }
    default_locale:  "fr"
    fragments:       ~
    http_method_override: true
    assets: ~

    # This is required for ewz_recaptcha
    templating:
      engines: ['twig']

twig:
    debug:            "%kernel.debug%"
    strict_variables: false
    form_themes:
#        # Symfony's core form themes, last one if default one
        - "bootstrap_3_layout.html.twig"
#        - "bootstrap_3_horizontal_layout.html.twig"
#        # Custom form theme
        - "Form/bootstrap_custom.html.twig"
#        # Custom form types
        - "Form/fields.html.twig"
#        # Bundle provided form themes and widgets
        - "AutocompleteBundle:Form:fields.html.twig"
        - "IbanBundle:Form:fields.html.twig"
        - "FilechunkBundle:Form:fields.html.twig"

#doctrine:
#    dbal: {}
#    orm:
#        # @todo cannot disable this until the cache warmer isn't full restored
#        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
#        mappings:
#            SaurFormBundle:
#                type: annotation

ewz_recaptcha:
    enabled: true
    ajax: false
    public_key: 6LfBhAwUAAAAAMR7rWIZIPKEMeSf2wVdZmDGR_sk
    private_key: 6LfBhAwUAAAAAChBr5KAkyDTu4iJT021Nzgp-eWg

redis:
    client:
        default:
            host: tcp://127.0.0.1
            type: phpredis
            persistent: false
            cluster: false
            timeout: 0.5
